//Macro definations  


#ifndef _DEFINES_H_
#define _DEFINES_H_
#define SETBIT(WORD,BITPOS) (WORD |=1<<BITPOS)
#define SSETBIT(WORD,BITPOS) (WORD=1<<BITPOS)
#define CLRBIT(WORD,BITPOS) (WORD&=~(1<<BITPOS))
#define SCLRBIT SSETBIT
#define CPLBIT(WORD,BITPOS) (WORD^=1<<BITPOS)
#define WRITEBIT(WORD,BITPOS,BIT) WORD=((WORD&~(1<<BITPOS))|(BIT<<BITPOS))
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define READWRITEBIT(WORD,DBIT,SBIT) WORD=(WORD&~(1<<DBIT))|(((WORD>>SBIT)&1)<<DBIT)
#define READWRITE2(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|       \
                                                 (((SWORD>>SBIT)&1)<<DBIT))
#define WRITENIBBLE(WORD,BITPOS,NIBBLE) WORD=(WORD&~(15<<BITPOS))|(NIBBLE<<BITPOS)
#define READNIBBLE(WORD,BITPOS) ((WORD>>BITPOS)&15)
#define WRITEBYTE(WORD,BITPOS,BYTE) WORD=((WORD&~(255<<BITPOS))|(BYTE<<BITPOS))
#define READBYTE(WORD,BITPOS) ((WORD>>BITPOS)&255)

#endif

